export default [

  {
      title:"I Asked ChatGPT to Create Comics, Then I Drew Them",
      body: "By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write... By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write...By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write...",
      image: "https://mui.com/static/images/cards/live-from-space.jpg",
      date:'Jan 22, 2022',
      chips:['React', 'Java', 'Chat GPT' ],
      path:"onions",
      minsToRead:2,
  },
  {
    title:"I Asked ChatGPT to Create Comics, Then I Drew Them",
    body: "By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write... By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write...By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write...",
    image: "https://mui.com/static/images/cards/live-from-space.jpg",
    date:'Jan 22, 2022',
    chips:['React', 'Java', 'AI' ],
    path:"onions",
    minsToRead:2,
},
{
  title:"I Asked ChatGPT to Create Comics, Then I Drew Them",
  body: "By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write... By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write...By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write...",
  image: "https://mui.com/static/images/cards/live-from-space.jpg",
  date:'Jan 22, 2022',
  chips:['React', 'Java', 'AI' ],
  path:"onions",
  minsToRead:2,
},
{
  title:"I Asked ChatGPT to Create Comics, Then I Drew Them",
  body: "By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write... By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write...By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write...",
  image: "https://mui.com/static/images/cards/live-from-space.jpg",
  date:'Jan 22, 2022',
  chips:['React', 'Java', 'AI' ],
  path:"onions",
  minsToRead:2,
},
{
  title:"I Asked ChatGPT to Create Comics, Then I Drew Them",
  body: "By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write... By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write...By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write...",
  image: "https://mui.com/static/images/cards/live-from-space.jpg",
  date:'Jan 22, 2022',
  chips:['React', 'Java', 'AI' ],
  path:"onions",
  minsToRead:2,
},
{
  title:"I Asked ChatGPT to Create Comics, Then I Drew Them",
  body: "By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write... By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write...By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write...",
  image: "https://mui.com/static/images/cards/live-from-space.jpg",
  date:'Jan 22, 2022',
  chips:['React', 'Java', 'AI' ],
  path:"onions",
  minsToRead:2,
},

]